### ISSUE TITLE
Render AcadVault content using React95 Trees

### ISSUE THREAD

**Issue by smit2k14** [Tikam02/AcadVault-ui#7]
Display the files in a tree like structure as shown [here](https://react95.github.io/React95/?path=/story/tree--simple). The individual should be able to navigate effortlessly and get to the required file and be able to download it. [This link](https://stackoverflow.com/questions/4604663/download-single-files-from-github) is a good reference as a how to guide.

**Comment by gauravsofat** [comment]
This is definitely the next logical step towards a fully functioning UI but I think it would be more prudent to break this issue down into two more granular tasks --
1. Display the repo as a tree-structured filesystem
2. Facilitate file downloads (singular/bulk file downloads)

In case there are multiple people working, this would also allow for parallel work on both fronts

**Comment by Ishakikani9117** [comment]
@gauravsofat  @smit2k14  Can you explain more about displaying the files as tree structure? This [link](https://react95.github.io/React95/?path=/story/tree--simple) doesn't have proper documentation.

**Comment by gauravsofat** [comment]
Sure. So the broad objective is that the user should be able to view/navigate contents of the AcadVault repo through the UI components built here. Now considering the way we've organised the AcadVault repo, an appropriate way to display them in our UI would be as a filesystem.

This is where the tree structure comes in. Just as shown in [this example](https://react95.github.io/React95/?path=/story/tree--simple), we're hoping to leverage this tree component from the React95 library, to display the entire contents of the AcadVault repo in a way that a user can easily find/access any file they might be looking for. This is an intuitive way to navigate through the repo contents.

From a dev standpoint, what this involves is transforming the data you've retrieved from the GitHub API in #3 and using it to display the entire contents of the AcadVault repo in a nested tree-like filesystem as shown in the storybook example. The user should be able to navigate this UI to reach any file within the repo. You can cache the tree structure to make this more efficient, rendering a new tree only if there is a change in the AcadVault repo (the sha1 value of the tree will help you here).

Hope this clears things a bit, but feel free to revert with any further queries.

**Comment by Ishakikani9117** [comment]
@gauravsofat  No, the problem is the repo I'm retrieving from API is in the form of an array. So how am I supposed to convert that array into a tree structure and use it in tree component?

**Comment by gauravsofat** [comment]
> This is definitely the next logical step towards a fully functioning UI but I think it would be more prudent to break this issue down into two more granular tasks --
> 
> 1. Display the repo as a tree-structured filesystem
> 2. Facilitate file downloads (singular/bulk file downloads)
> 
> In case there are multiple people working, this would also allow for parallel work on both fronts

Modified issue title to isolate issues as per this comment. @smit2k14 + @kartikeya99 can you create a new issue about downloading repo artifacts?

**Comment by Ishakikani9117** [comment]
@gauravsofat  Can you please create an issue regarding the file downloads?
